import { devuiDarkTheme, devuiLightTheme, Theme } from 'ng-devui/theme';
export const infinityTheme: Theme = new Theme({
    id: 'infinity-theme',
    name: '无限主题',
    data: Object.assign({}, devuiLightTheme.data, {
        'devui-brand-foil': '#F2F2F3',
        'devui-global-bg': '#F8F8FA',
        'devui-base-bg': '#ffffff',
        'devui-text': '#252B3A',
        'devui-aide-text': '#71757f',
        'devui-placeholder': '#babbc0',
        'devui-disabled-text': '#cfd0d3',
        'devui-disabled-bg': '#f5f5f6',
        'devui-line': '#D7D8DA',
        'devui-dividing-line': '#F2F2F3',
        'devui-list-item-hover-bg': '#F2F2F3',
        'devui-list-item-active-bg': '#F2F5FC',
        'devui-list-item-active-hover-bg': '#F2F5FC',
        'devui-list-item-selected-bg': '#F2F5FC',
        'devui-list-item-hover-text': '#252b3a',
        'devui-list-item-active-text': '#252B3A',
        'devui-form-control-line-hover': '#A3A6AC',
        'devui-form-control-line': '#D7D8DA',
        'devui-icon-text': '#babbc0',
        'devui-label-bg': '#E9EDFA',
        'devui-border-radius': '4px',
        'devui-font-size': '14px',
        'devui-font-size-md': '14px',
        'devui-font-size-card-title': '16px',
        'devui-shadow-length-fullscreen-overlay': '0 0 6px 0',
        'devui-border-radius-card': '4px'
    }),
    extends: 'devui-light-theme',
    isDark: false,
});

export const provenceTheme: Theme = new Theme({
    id: 'provence-theme',
    name: '紫罗兰主题',
    data: {
        ...infinityTheme.data,
        'devui-brand': '#7B69EE',
        'devui-brand-foil': '#F5F5F9',
        'devui-brand-active-focus': '#7B69EE',
        'devui-primary-active': '#7B69EE',
        'devui-brand-hover': '#7B69EE',
        'devui-global-bg': '#f9fafb',
        'devui-base-bg': '#ffffff',
        'devui-text': '#070036',
        'devui-aide-text': '#717087',
        'devui-placeholder': '#babbc0',
        'devui-disabled-text': '#cfd0d3',
        'devui-disabled-bg': '#f5f5f6',
        'devui-line': '#E2E2E5',
        'devui-dividing-line': '#F2F2F3',
        'devui-list-item-hover-bg': '#F5F5F9',
        'devui-list-item-active-bg': '#7B69EE',
        'devui-list-item-active-hover-bg': '#7B69EE',
        'devui-list-item-selected-bg': '#F4F2FF',
        'devui-list-item-hover-text': '#252b3a',
        'devui-list-item-active-text': '#ffffff',
        'devui-form-control-line-hover': '#A3A6AC',
        'devui-form-control-line': '#D7D8DA',
        'devui-icon-text': '#babbc0',
        'devui-brand-active': '#7B69EE',
        'devui-primary': '#7B69EE',
        'devui-primary-hover': '#7B69EE',
        'devui-form-control-line-active': '#7B69EE',
        'devui-form-control-line-active-hover': '#7B69EE',
        'devui-icon-fill-active': '#7B69EE',
        'devui-icon-fill-active-hover': '#7B69EE',
        'devui-label-bg': '#F4F2FF',
        'devui-embed-search-bg': '#F4F2FF',
        'devui-connected-overlay-line': '#7B69EE',
        'devui-primary-disabled': '#d8d2fa',
        'devui-icon-fill-active-disabled': '#d8d2fa'

    },
    extends: 'infinity-theme',
    isDark: false
});

export const sweetTheme: Theme = new Theme({
    id: 'sweet-theme',
    name: '蜜糖主题',
    data: {
        ...infinityTheme.data,
        'devui-brand': '#ec66ab',
        'devui-brand-foil': '#f8f1f5',
        'devui-brand-active-focus': '#ec66ab',
        'devui-primary-active': '#ec66ab',
        'devui-brand-hover': '#ec66ab',
        'devui-global-bg': '#f9fafb',
        'devui-base-bg': '#ffffff',
        'devui-text': '#2f272f',
        'devui-aide-text': '#827d82',
        'devui-placeholder': '#bdb8bd',
        'devui-disabled-text': '#cbcacb',
        'devui-disabled-bg': '#f6f6f6',
        'devui-line': '#aea6ad',
        'devui-dividing-line': '#eae7e9',
        'devui-list-item-hover-bg': '#f8f1f5',
        'devui-list-item-active-bg': '#ffdcee',
        'devui-list-item-active-hover-bg': '#ffdcee',
        'devui-list-item-selected-bg': '#ffdcee',
        'devui-list-item-hover-text': '#252b3a',
        'devui-list-item-active-text': '#252b3a',
        'devui-form-control-line-hover': '#A3A6AC',
        'devui-form-control-line': '#D7D8DA',
        'devui-icon-text': '#babbc0',
        'devui-brand-active': '#ec66ab',
        'devui-primary': '#ec66ab',
        'devui-primary-hover': '#ec66ab',
        'devui-form-control-line-active': '#ec66ab',
        'devui-form-control-line-active-hover': '#ec66ab',
        'devui-icon-fill-active': '#ec66ab',
        'devui-icon-fill-active-hover': '#ec66ab',
        'devui-label-bg': '#ffdcee',
        'devui-embed-search-bg': '#ffdcee',
        'devui-connected-overlay-line': '#ec66ab',
        'devui-primary-disabled': '#fad1e6',
        'devui-icon-fill-active-disabled': '#fad1e6',
    },
    extends: 'infinity-theme',
    isDark: false
});

export const deepTheme: Theme = new Theme({
    id: 'deep-theme',
    name: '深邃夜空主题',
    data: {
        ...infinityTheme.data,
        'devui-brand': '#252b3a',
        'devui-brand-foil': '#f3f4f7',
        'devui-brand-active-focus': '#252b3a',
        'devui-primary-active': '#252b3a',
        'devui-brand-active': '#252b3a',
        'devui-brand-hover': '#252b3a',
        'devui-global-bg': '#f7f8fa',
        'devui-base-bg': '#ffffff',
        'devui-text': '#252b3a',
        'devui-aide-text': '#505c7c',
        'devui-placeholder': '#9ba6bf',
        'devui-disabled-text': '#a8b1c7',
        'devui-disabled-bg': '#f7f8fa',
        'devui-line': '#cdd2df',
        'devui-dividing-line': '#e6e9ef',
        'devui-list-item-hover-bg': '#f3f4f7',
        'devui-list-item-active-bg': '#252b3a',
        'devui-list-item-active-hover-bg': '#252b3a',
        'devui-list-item-selected-bg': '#252b3a',
        'devui-list-item-hover-text': '#252b3a',
        'devui-list-item-active-text': '#ffffff',
        'devui-form-control-line-hover': '#A3A6AC',
        'devui-form-control-line': '#D7D8DA',
        'devui-icon-text': '#babbc0',
        'devui-primary': '#252b3a',
        'devui-primary-hover': '#252b3a',
        'devui-form-control-line-active': '#252b3a',
        'devui-form-control-line-active-hover': '#252b3a',
        'devui-icon-fill-active': '#252b3a',
        'devui-icon-fill-active-hover': '#252b3a',
        'devui-connected-overlay-line': '#252b3a',
        'devui-primary-disabled': '#bebfc4',
        'devui-icon-fill-active-disabled': '#bebfc4',
    },
    extends: 'infinity-theme',
    isDark: false
});

export const galaxyTheme: Theme = new Theme({
    id: 'galaxy-theme',
    name: '追光主题',
    data: {
        ...devuiDarkTheme.data,
        'devui-brand-foil': '#F2F2F3',
        'devui-global-bg': '#000000',
        'devui-base-bg': '#1F1F1F',
        'devui-text': '#F5F5F5',
        'devui-aide-text': '#A3A3A3',
        'devui-placeholder': '#616161',
        'devui-disabled-text': '#838383',
        'devui-disabled-bg': '#3F3F3F',
        'devui-line': '#565656',
        'devui-dividing-line': '#303030',
        'devui-list-item-hover-bg': '#313131',
        'devui-list-item-active-bg': '#30333D',
        'devui-list-item-active-hover-bg': '#30333D',
        'devui-list-item-selected-bg': '#30333D',
        'devui-list-item-hover-text': '#F5F5F5',
        'devui-list-item-active-text': '#526ECC',
        'devui-primary-disabled': '#3f3f3f',
        'devui-form-control-line': '#565656',
        'devui-icon-text': '#A3A3A3',
        'devui-connected-overlay-bg': '#282828',
        'devui-fullscreen-overlay-bg': '#282828',
        'devui-warning-line': '#a2622a',
        'devui-warning-bg': '#4b2e14',
        'devui-success-line': '#27846b ',
        'devui-success-bg': '#123d32',
        'devui-danger-line': '#9f4844',
        'devui-danger-bg': '#4a2120',
        'devui-info-line': '#3c5091',
        'devui-info-bg': '#1c2543',
        'devui-default-bg': '#313131',
        'devui-border-radius': '4px',
        'devui-font-size': '14px',
        'devui-font-size-md': '14px',
        'devui-font-size-card-title': '16px',
        'devui-shadow-length-fullscreen-overlay': '0 0 6px 0',
        'devui-border-radius-card': '4px'
    },
    extends: 'devui-dark-theme',
    isDark: true
});
