import { devuiDarkTheme, Theme } from 'ng-devui/theme';
import {
  devuiCustomComponentsDarkThemeData,
  devuiCustomComponentsDeepThemeData,
  devuiCustomComponentsThemeData
} from './theme-custom-components-data';
import { devuiInitialThemeData } from './theme-initial-data';
export const infinityTheme: Theme = new Theme({
  id: 'infinity-theme',
  name: '无限主题',
  data: { ...devuiInitialThemeData, ...devuiCustomComponentsThemeData },
  extends: 'devui-light-theme',
  isDark: false,
});

export const newInfinityTheme: Theme = new Theme({
  id: 'new-infinity-theme',
  name: '新无限主题',
  data: {
    'devui-global-bg': '#f5f5f5',
    'devui-glass-morphism-bg': 'rgba(245, 246, 248, 0.9)',
    'devui-global-bg-normal': '#ffffff',
    'devui-base-bg': '#ffffff',
    'devui-base-bg-dark': '#000000',
    'devui-brand': '#5e7ce0',
    'devui-brand-foil': '#f2f2f3',
    'devui-brand-hover': '#7693f5',
    'devui-brand-active': '#526ecc',
    'devui-brand-active-focus': '#344899',
    'devui-contrast': '#c7000b',
    'devui-text': '#191919',
    'devui-text-weak': '#333333',
    'devui-aide-text': '#595959',
    'devui-aide-text-hover': '#000000',
    'devui-aide-text-stress': '#333333',
    'devui-placeholder': '#808080',
    'devui-light-text': '#ffffff',
    'devui-dark-text': '#000000',
    'devui-link': '#526ecc',
    'devui-link-active': '#526ecc',
    'devui-link-light': '#96adfa',
    'devui-link-light-active': '#beccfa',
    'devui-line': '#dbdbdb',
    'devui-dividing-line': '#e6e6e6',
    'devui-block': '#ffffff',
    'devui-area': '#f5f5f5',
    'devui-danger': '#f23030',
    'devui-warning': '#ffb700',
    'devui-waiting': '#beccfa',
    'devui-success': '#029931',
    'devui-info': '#5e7ce0',
    'devui-initial': '#e9edfa',
    'devui-unavailable': '#f5f5f5',
    'devui-shadow': 'rgba(0, 0, 0, 0.16)',
    'devui-light-shadow': 'rgba(0, 0, 0, 0.08)',
    'devui-connected-overlay-shadow': 'rgba(0, 0, 0, 0.16)',
    'devui-feedback-overlay-shadow': 'rgba(0, 0, 0, 0.16)',
    'devui-feedback-overlay-backdrop': 'rgba(0, 0, 0, 0.3)',
    'devui-hover-shadow': 'rgba(0, 0, 0, 0.16)',
    'devui-table-column-shadow-color': 'rgba(37, 43, 58, 0.08)',
    'devui-icon-text': '#808080',
    'devui-icon-bg': '#ffffff',
    'devui-icon-fill': '#595959',
    'devui-icon-fill-weak': '#808080',
    'devui-icon-fill-hover': '#191919',
    'devui-icon-fill-active': '#191919',
    'devui-icon-fill-active-hover': '#000000',
    'devui-shape-icon-fill': '#c2c2c2',
    'devui-shape-icon-fill-hover': '#808080',
    'devui-shape-icon-fill-active': '#808080',
    'devui-shape-icon-fill-disabled': '#f0f0f0',
    'devui-form-control-line': '#dbdbdb',
    'devui-form-control-bg': '#ffffff',
    'devui-form-control-line-hover': '#808080',
    'devui-form-control-line-active': '#5e7ce0',
    'devui-form-control-interactive-outline': 'rgba(94, 124, 224, 0.08)',
    'devui-form-control-line-active-hover': '#344899',
    'devui-list-item-active-bg': '#e9edfa',
    'devui-list-item-active-text': '#000000',
    'devui-list-item-active-hover-bg': '#e9edfa',
    'devui-list-item-hover-bg': '#f2f2f3',
    'devui-list-item-hover-text': '#000000',
    'devui-list-item-selected-bg': '#e9edfa',
    'devui-list-item-strip-bg': '#f2f5fc',
    'devui-disabled-bg': '#f5f5f5',
    'devui-disabled-line': '#e6e6e6',
    'devui-disabled-text': '#c2c2c2',
    'devui-primary-disabled': '#beccfa',
    'devui-icon-fill-active-disabled': '#beccfa',
    'devui-label-bg': '#f0f0f0',
    'devui-connected-overlay-bg': '#ffffff',
    'devui-connected-overlay-line': '#526ecc',
    'devui-fullscreen-overlay-bg': '#ffffff',
    'devui-feedback-overlay-bg': '#333333',
    'devui-feedback-overlay-text': '#f0f0f0',
    'devui-embed-search-bg': '#f2f2f3',
    'devui-embed-search-bg-hover': '#f5f5f5',
    'devui-float-block-shadow': 'rgba(94, 124, 224, 0.3)',
    'devui-highlight-overlay': 'rgba(255, 255, 255, 0.8)',
    'devui-range-item-hover-bg': '#e9edfa',
    'devui-gray-form-control-bg': '#f5f5f5',
    'devui-gray-form-control-hover-bg': '#ebebeb',
    'devui-nav-expand-bg': '#fbfbfc',
    'devui-primary': '#5e7ce0',
    'devui-primary-hover': '#7693f5',
    'devui-primary-active': '#344899',
    'devui-contrast-hover': '#cc272a',
    'devui-contrast-active': '#78080e',
    'devui-danger-line': '#f23030',
    'devui-danger-bg': '#fce2e0',
    'devui-danger-text': '#a3171c',
    'devui-warning-line': '#ff8800',
    'devui-warning-bg': '#ffebd1',
    'devui-warning-text': '#d96900',
    'devui-info-line': '#5e7ce0',
    'devui-info-bg': '#e9edfa',
    'devui-success-line': '#00b336',
    'devui-success-bg': '#d5f2dc',
    'devui-success-text': '#01802b',
    'devui-primary-line': '#5e7ce0',
    'devui-primary-bg': '#f2f5fc',
    'devui-default-line': '#5e7ce0',
    'devui-default-bg': '#fafafa',
    'devui-shadow-length-base': '0 1px 6px 0',
    'devui-shadow-length-slide-left': '-2px 0 8px 0',
    'devui-shadow-length-slide-right': '2px 0 8px 0',
    'devui-shadow-length-connected-overlay': '0 4px 12px 0',
    'devui-shadow-length-hover': '0 8px 24px 0',
    'devui-shadow-length-feedback-overlay': '0 8px 24px 0',
    'devui-shadow-length-fullscreen-overlay': '0 16px 48px 0',
    'devui-border-radius': '4px',
    'devui-border-radius-feedback': '4px',
    'devui-border-radius-card': '8px',
    'devui-border-radius-full': '100px',
    'devui-font-size': '14px',
    'devui-font-size-card-title': '16px',
    'devui-font-size-page-title': '16px',
    'devui-font-size-modal-title': '18px',
    'devui-font-size-price': '20px',
    'devui-font-size-data-overview': '24px',
    'devui-font-size-icon': '16px',
    'devui-font-size-sm': '12px',
    'devui-font-size-md': '14px',
    'devui-font-size-lg': '14px',
    'devui-font-title-weight': 'bold',
    'devui-font-content-weight': 'normal',
    'devui-line-height-base': '1.5',
    'devui-animation-ease-in-smooth': 'cubic-bezier(0.645, 0.045, 0.355, 1)',
    'devui-animation-duration-slow': '300ms',
    'devui-animation-duration-base': '200ms',
    'devui-animation-duration-fast': '100ms',
    'devui-animation-ease-in': 'cubic-bezier(0.5, 0, 0.84, 0.25)',
    'devui-animation-ease-out': 'cubic-bezier(0.16, 0.75, 0.5, 1)',
    'devui-animation-ease-in-out': 'cubic-bezier(0.5, 0.05, 0.5, 0.95)',
    'devui-animation-ease-in-out-smooth': 'cubic-bezier(0.645, 0.045, 0.355, 1)',
    'devui-animation-linear': 'cubic-bezier(0, 0, 1, 1)',
    'devui-z-index-full-page-overlay': '1080',
    'devui-z-index-pop-up': '1060',
    'devui-z-index-dropdown': '1052',
    'devui-z-index-modal': '1050',
    'devui-z-index-drawer': '1040',
    'devui-z-index-framework': '1000',
    'devui-btn-common-bg-disabled': '#F0F0F0',
  },
  extends: 'devui-light-theme',
  isDark: false,
});

export const provenceTheme: Theme = new Theme({
  id: 'provence-theme',
  name: '普罗旺斯主题',
  data: {
    ...infinityTheme.data,
    'devui-brand': '#7B69EE',
    'devui-brand-foil': '#F5F5F9',
    'devui-brand-active-focus': '#7B69EE',
    'devui-primary-active': '#7B69EE',
    'devui-brand-hover': '#7B69EE',
    'devui-global-bg': '#f9fafb',
    'devui-glass-morphism-bg': 'rgba(245, 246, 248,0.9)',
    'devui-base-bg': '#ffffff',
    'devui-text': '#070036',
    'devui-aide-text': '#717087',
    'devui-placeholder': '#babbc0',
    'devui-disabled-text': '#babbc0',
    'devui-disabled-bg': '#f5f5f6',
    'devui-line': '#E2E2E5',
    'devui-dividing-line': '#F2F2F3',
    'devui-list-item-hover-bg': '#F5F5F9',
    'devui-list-item-active-bg': '#f9ebff',
    'devui-list-item-active-hover-bg': '#7B69EE',
    'devui-list-item-selected-bg': '#F4F2FF',
    'devui-list-item-hover-text': '#252b3a',
    'devui-list-item-active-text': '#252b3a',
    'devui-form-control-line': '#D7D8DA',
    'devui-icon-text': '#babbc0',
    'devui-brand-active': '#7B69EE',
    'devui-primary': '#7B69EE',
    'devui-primary-hover': '#7B69EE',
    'devui-form-control-line-active': '#7B69EE',
    'devui-form-control-interactive-outline': 'rgba(123,105,238,0.08)',
    'devui-form-control-line-active-hover': '#7B69EE',
    'devui-icon-fill-active': '#7B69EE',
    'devui-icon-fill-active-hover': '#7B69EE',
    'devui-label-bg': '#F4F2FF',
    'devui-embed-search-bg': '#F4F2FF',
    'devui-connected-overlay-line': '#7B69EE',
    'devui-primary-disabled': '#d8d2fa',
    'devui-icon-fill-active-disabled': '#d8d2fa',
    'devui-link-active': '#3f1a9c',
    'devui-gray-form-control-bg': '#f5f5f5',
    'devui-gray-form-control-hover-bg': '#ebebeb',
    'devui-range-item-hover-bg': '#f4e0fc',
  },
  extends: 'infinity-theme',
  isDark: false,
});

export const sweetTheme: Theme = new Theme({
  id: 'sweet-theme',
  name: '蜜糖主题',
  data: {
    ...infinityTheme.data,
    'devui-brand': '#ec66ab',
    'devui-brand-foil': '#f8f1f5',
    'devui-brand-active-focus': '#ec66ab',
    'devui-primary-active': '#ec66ab',
    'devui-brand-hover': '#ec66ab',
    'devui-global-bg': '#f9fafb',
    'devui-glass-morphism-bg': 'rgba(245, 246, 248,0.9)',
    'devui-base-bg': '#ffffff',
    'devui-text': '#2f272f',
    'devui-aide-text': '#827d82',
    'devui-placeholder': '#bdb8bd',
    'devui-disabled-text': '#bdb8bd',
    'devui-disabled-bg': '#f6f6f6',
    'devui-line': '#aea6ad',
    'devui-dividing-line': '#eae7e9',
    'devui-list-item-hover-bg': '#f8f1f5',
    'devui-list-item-active-bg': '#ffdcee',
    'devui-list-item-active-hover-bg': '#ffdcee',
    'devui-list-item-selected-bg': '#ffdcee',
    'devui-list-item-hover-text': '#252b3a',
    'devui-list-item-active-text': '#252b3a',
    'devui-form-control-line': '#D7D8DA',
    'devui-icon-text': '#babbc0',
    'devui-brand-active': '#ec66ab',
    'devui-primary': '#ec66ab',
    'devui-primary-hover': '#ec66ab',
    'devui-form-control-line-active': '#ec66ab',
    'devui-form-control-interactive-outline': 'rgba(236,102,171,0.08)',
    'devui-form-control-line-active-hover': '#ec66ab',
    'devui-icon-fill-active': '#ec66ab',
    'devui-icon-fill-active-hover': '#ec66ab',
    'devui-label-bg': '#ffdcee',
    'devui-embed-search-bg': '#ffdcee',
    'devui-connected-overlay-line': '#ec66ab',
    'devui-primary-disabled': '#fad1e6',
    'devui-icon-fill-active-disabled': '#fad1e6',
    'devui-link-active': '#96114d',
    'devui-gray-form-control-bg': '#f5f5f5',
    'devui-gray-form-control-hover-bg': '#ebebeb',
    'devui-range-item-hover-bg': '#ffd6e8',
  },
  extends: 'infinity-theme',
  isDark: false,
});

export const deepTheme: Theme = new Theme({
  id: 'deep-theme',
  name: '深邃夜空主题',
  data: {
    ...infinityTheme.data,
    ...devuiCustomComponentsDeepThemeData,
    'devui-global-bg': '#f5f5f5',
    'devui-glass-morphism-bg': 'rgba(242,242,243,0.9)',
    'devui-brand': '#191919',
    'devui-brand-foil': '#f3f4f7',
    'devui-brand-active-focus': '#191919',
    'devui-brand-active': '#191919',
    'devui-brand-hover': '#191919',
    'devui-disabled-text': '#999999',
    'devui-disabled-bg': '#EBEBEB',
    'devui-line': '#C2C2C2',
    'devui-dividing-line': '#D5D5DB',
    'devui-disabled-line': '#DBDBDB',
    'devui-list-item-hover-bg': '#F0F0F0',
    'devui-list-item-active-bg': '#E6E6E6',
    'devui-list-item-active-hover-bg': '#d5d5db',
    'devui-list-item-selected-bg': '#d5d5db',
    'devui-list-item-hover-text': '#191919',
    'devui-list-item-active-text': '#191919',
    'devui-primary': '#191919',
    'devui-primary-hover': '#595959',
    'devui-primary-active': '#333333',
    'devui-primary-disabled': '#C2C2C2',
    'devui-form-control-line': '#C2C2C2',
    'devui-form-control-line-hover': '#191919',
    'devui-form-control-line-active': '#191919',
    'devui-form-control-interactive-outline': 'rgba(37,43,58,0.08)',
    'devui-form-control-line-active-hover': '#595959',
    'devui-connected-overlay-line': '#191919',
    'devui-gray-form-control-hover-bg': '#DBDBDB',
    'devui-nav-expand-bg': '#f7f7f8',
    'devui-range-item-hover-bg': '#f5f5f5',
    'devui-icon-fill-active-disabled': '#595959',
  },
  extends: 'infinity-theme',
  isDark: false,
});

export const galaxyTheme: Theme = new Theme({
  id: 'galaxy-theme',
  name: '追光主题',
  data: {
    ...devuiDarkTheme.data,
    ...devuiCustomComponentsDarkThemeData,
    // use '526ECC' for active status except 'devui-list-item-active-bg'
    'devui-brand': '#526ECC',
    'devui-info': '#526ECC',
    'devui-primary': '#526ECC',
    'devui-default-line': '#526ECC',
    'devui-brand-hover': '#5E7CE0',
    'devui-primary-hover': '#5E7CE0',
    'devui-brand-foil': '#F2F2F3',
    'devui-global-bg': '#1A1A1C',
    'devui-glass-morphism-bg': 'rgba(26,26,28,0.9)',
    'devui-base-bg': '#292A2E',
    'devui-text': '#CED1DB',
    'devui-aide-text': '#868A99',
    'devui-placeholder': '#5B5D66',
    'devui-disabled-text': '#5b5d66',
    'devui-disabled-bg': '#2D2E32',
    'devui-line': '#4e5057',
    'devui-dividing-line': '#323438',
    'devui-list-item-hover-bg': '#3d3d42',
    'devui-list-item-active-bg': '#33384B',
    'devui-list-item-active-hover-bg': '#33384B',
    'devui-list-item-selected-bg': '#33384B',
    'devui-list-item-hover-text': '#F5F5F5',
    'devui-list-item-active-text': '#526ECC',
    'devui-primary-disabled': '#3f3f3f',
    'devui-form-control-line': '#4e5057',
    'devui-form-control-bg': '#292A2E',
    'devui-form-control-line-hover': '#696c75',
    'devui-form-control-line-active': '#526ECC',
    'devui-form-control-interactive-outline': 'rgba(82,110,204,0.08)',
    'devui-icon-text': '#868A99',
    'devui-connected-overlay-bg': '#2E2F33',
    'devui-fullscreen-overlay-bg': '#2E2F33',
    'devui-warning-line': '#EB8F3D',
    'devui-warning-bg': '#4b2e14',
    'devui-success-line': '#2AA37E ',
    'devui-success-bg': '#123d32',
    'devui-danger-line': '#D15854',
    'devui-danger-bg': '#4a2120',
    'devui-info-line': '#4482BD',
    'devui-info-bg': '#1c2543',
    'devui-default-bg': '#313131',
    'devui-label-bg': '#353537',
    'devui-icon-fill': '#868A99',
    'devui-icon-fill-hover': '#ced1db',
    'devui-icon-fill-active': '#ced1db',
    'devui-icon-fill-active-hover': '#ced1db',
    'devui-border-radius': '4px',
    'devui-border-radius-feedback': '4px',
    'devui-border-radius-card': '8px',
    'devui-font-size': '14px',
    'devui-font-size-md': '14px',
    'devui-font-size-card-title': '16px',
    'devui-shadow-length-fullscreen-overlay': '0 0 6px 0',
    'devui-gray-form-control-bg': '#323338',
    'devui-gray-form-control-hover-bg': '#393A3E',
    'devui-nav-expand-bg': '#1d1d21',
    'devui-link': '#7693F5',
    'devui-link-active': '#465EB8',
    'devui-table-column-shadow-color': 'rgba(0,0,0,0.24)',
  },
  extends: 'devui-dark-theme',
  isDark: true,
});
